# Change these first
owner: 0xflotus # Your GitHub username
repo: github-page-monitoring # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal Github Page
    url: https://0xflotus.github.io
  - name: Is a dev Page
    url: https://0xflotus.is-a.dev
    
assignees: 0xflotus

status-website:
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /github-page-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 * * * *"
  responseTime: "0 * * * *"
  staticSite: "*/5 * * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "*/5 * * * *"
  uptime: "*/5 * * * *"
